sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    access-key-id: LTAI5tAv1h9VrTrTapE2yvVn
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-secret: 41EslHMW5rfRgYRuH4Em95zI1Ljjpx
    bucket-name: sky-yxl
  redis:
    host: 192.168.72.149
    password: 123456
    port: 6379
    database: 10
  wechat:
    appid: wxa5807f817bd29a8e
    secret: 86a86f3eddc7653b6c72ab0f58909577
  shop:
    address: 北京市海淀区上地十街10号
  baidu:
    ak: AQfu8sXx5eoZqD6AynvEEuUeQoiqzFMO

